- name: upgrade all yum packages
  yum: name=* state=latest

- name: get epel-repo rpm RHEL6
  get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

- name: install epel-repo rpm
  yum: pkg=/tmp/epel-release.rpm state=installed

- name: get rpmforge-repo rpm RHEL6
  get_url: dest=/tmp/rpmforge-release.rpm  url=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm

- name: install rpmforge-repo rpm
  yum: pkg=/tmp/rpmforge-release.rpm state=installed

- name: be sure httpd is installed
  yum: name=httpd state=latest

- name: create document root
  file: dest={{ work_dir }} state=directory owner=apache group=apache mode=0755

- name: change listen port to 8080
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen " insertafter="^#Listen " line="Listen 8080"

- name: remove httpd welcome.conf
  file: path=/etc/httpd/conf.d/welcome.conf state=absent

- name: be sure httpd is configured
  template: src=common.conf.j2 dest=/etc/httpd/conf.d/common.conf

- name: put basic authentication file
  htpasswd: path={{ auth_file }} name={{ auth_user }} password={{ auth_pswd }} owner=root group=root mode=0644

- name: put .htaccess under the document root
  template: src=htaccess.j2 dest={{ work_dir }}/.htaccess

- name: restart httpd
  service: name=httpd state=restarted

- name: set hosts file
  lineinfile: dest=/etc/hosts backup=yes insertafter="{{item.insertafter}}" line="{{item.line}}"
  with_items: 
      - { line: "{{ ansible_eth0.ipv4.address }} wordpress-do wordpress-do", insertafter: EOF }
      - { line: "{{ ansible_eth0.ipv4.address }} mt-do mt-do", insertafter: EOF }
      - { line: "{{ ansible_eth0.ipv4.address }} drupal-do drupal-do", insertafter: EOF }

- name: be sure httpd is running and enabled
  service: name=httpd state=running enabled=yes


# clone htm sources from git repo 
#    - name: git clone from src
#      git: repo=git@bitbucket.org:chienowa/costpa.git dest={{repos_dir}} version={{branch}} accept_hostkey=yes 
