---
- hosts: all
  sudo: yes
  vars:
    dbname: drupal
    dbuser: drupal
    dbpassword: drupal
    docroot: /var/www/drupal
    version: "7.31" 

  tasks:
    - name: be sure httpd is installed
      yum: name=httpd state=latest
      tags: httpd

    - name: create document root
      file: dest={{ docroot }} state=directory owner=apache group=apache mode=0755

    - name: be sure httpd is configured
      template: src=drupal.conf.j2 dest=/etc/httpd/conf.d/drupal.conf
      tags: httpd

    - name: restart httpd
      service: name=httpd state=restarted

    - name: remove httpd welcome.conf
      file: path=/etc/httpd/conf.d/welcome.conf state=absent
      tags: httpd

    - name: restart httpd
      service: name=httpd state=restarted

    - name: be sure httpd is running and enabled
      service: name=httpd state=running enabled=yes
      tags: httpd  


    - name: restart httpd
      service: name=httpd state=restarted

    - name: change drupal files owner
      command: chown -R apache:apache {{ docroot }}

    - name: be sure mysql-server is installed
      yum: name={{item}} state=installed
      with_items:
             - mysql-server
             - MySQL-python
      tags: mysqld

    - name: be sure mysqld is running and enabled
      service: name=mysqld state=started enabled=yes
      tags: mysqld

    - name: Create database
      mysql_db: db={{dbname}} state=present encoding=utf8
      tags: mysqld

    - name: Create database user
      mysql_user: >
             name={{dbuser}}
             password={{dbpassword}}
             priv={{dbname}}.*:ALL
             state=present
      tags: mysqld 

    - name: be sure php is installed
      yum: name={{item}} state=installed enablerepo=epel
      with_items:
            - php
            - php-mysql
            - php-mbstring
            - php-gd
            - php-pear
            - php-pecl-apcu
            - php-xml  
      tags: php

    - name: set timezone in php.ini
      lineinfile: >
            dest=/etc/php.ini
            regexp='^;?date.timezone ='
            line='date.timezone = Asia/Tokyo'
            owner=root
            group=root
            mode=0644
      tags: php

    - name: restart httpd
      service: name=httpd state=restarted


    - name: download drupal package
      git : repo=http://git.drupal.org/project/drupal.git dest="{{docroot}}" version={{version}}
      tags: drupal

    - name: change drupal files owner
      command: chown -R apache:apache {{docroot}}


