---
- hosts: all
  sudo: yes
  vars:
    ssh_user: ec2-user    
    mtroot: /var/www/mtroot
    dbname: mtos
    dbuser: mtos
    dbpassword: mtos 

  tasks:
    - name: upgrade all yum packages
      yum: name=* state=latest

    - name: get epel-repo rpm RHEL6
      get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
   
    - name: install epel-repo rpm
      yum: pkg=/tmp/epel-release.rpm state=installed

    - name: get rpmforge-repo rpm RHEL6
      get_url: dest=/tmp/rpmforge-release.rpm  url=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
   
    - name: install rpmforge-repo rpm
      yum: pkg=/tmp/rpmforge-release.rpm state=installed

    - name: install required yum packages           
      yum: name={{item}} state=latest
      with_items:
             - httpd
             - git
             - ImageMagick
             - ImageMagick-devel  
      tags: common 

    - name: be sure mtroot is not there
      file: path={{mtroot}} state=absent

    - name: git clone from src and make document root
      git: repo=https://github.com/movabletype/movabletype.git dest="{{mtroot}}/mt" #version=mtos5.2.10

    - name: make movabletype
      command: make me 
      args: 
        chdir: "{{ mtroot }}/mt/"
 
    - name: be sure httpd is configured
      template: src=mt.conf.j2 dest=/etc/httpd/conf.d/mt.conf
      tags: common

    - name: restart httpd
      service: name=httpd state=restarted

    - name: be sure httpd is running and enabled
      service: name=httpd state=running enabled=yes
      tags: common

    - name: change mt files owner
      command: chown -R {{ssh_user}}:{{ ssh_user }} {{ mtroot }}
 
    - name: change mt directory permission
      file: path={{mtroot}} state=directory recurse=yes mode=0707

    - name: be sure mysql-server is installed
      yum: name={{item}} state=installed
      with_items:
             - mysql-server
             - MySQL-python
      tags: mysqld

    - name: be sure mysqld is running and enabled
      service: name=mysqld state=started enabled=yes
      tags: mysqld

    - name: Create database
      mysql_db: db={{dbname}} state=present encoding=utf8
      tags: mysqld

    - name: Create database user
      mysql_user: >
             name={{dbuser}}
             password={{dbpassword}}
             priv={{dbname}}.*:ALL
             state=present
      tags: mysqld 

    - name: be sure php is installed
      yum: name={{item}} state=installed enablerepo=epel
      with_items:
            - php
            - php-mysql
            - php-mbstring
            - php-gd
            - php-pear
            - php-pecl-apcu
      tags: php

    - name: set timezone in php.ini
      lineinfile: >
            dest=/etc/php.ini
            regexp='^;?date.timezone ='
            line='date.timezone = Asia/Tokyo'
            owner=root
            group=root
            mode=0644
      tags: php

    - name: configure mt-readme.html
      template: src=mt-readme.html.j2 dest={{mtroot}}/index.html owner={{ssh_user}} group={{ssh_user}} mode=0644
      tags: mt

    - name: be sure perl libraries for mt are installed
      yum: name={{item}} state=installed enablerepo=rpmforge disablerepo=epel
      with_items:
              - perl-Archive-Tar
              - perl-Archive-Zip
              - perl-Authen-SASL
              - perl-Class-DBI-mysql
              - perl-Crypt-DSA
              - perl-Crypt-SSLeay
              - perl-Digest-SHA
              - perl-Digest-SHA1
              - perl-GD
              - perl-HTML-Parser
              - perl-Net-SSLeay
              - perl-IO-Socket-SSL
              - perl-IO-Compress-Zlib 
              - perl-IPC-Run
              - perl-Mail-Sendmail
              - perl-Net-SMTP-SSL
      tags: ansible

    - name: restart httpd
      service: name=httpd state=restarted


