---
- hosts: all
  sudo: yes
  connection: local
  vars:
     listen_port: 80
     cache_ttl: 180 # ttl seconds
     cache_storage: "malloc,100M" # memory cache
     host_tag: costpa
     host_name: costpa.net         
  tasks:
    - name: be sure varnish 3 rpm is installed
      yum: name=https://repo.varnish-cache.org/redhat/varnish-3.0.el6.rpm state=present
      tags: varnish

    - name: install varnish
      yum: name=varnish state=present

    - name: configure varnish vcl
      template: src=default.vcl dest=/etc/varnish/default.vcl

    - name: configure /etc/sysconfig/varnish
      template: src=etc-sysconfig-varnish dest=/etc/sysconfig/varnish 
      tags: varnish

    - name: restart varnish
      service: name=varnish state=restarted

    - name: be sure varnish is running and enabled
      service: name=varnish state=running enabled=yes
      tags: varnish  




