- name: be sure httpd is running and enabled
  service: name=httpd state=running enabled=yes


- name: install required yum packages           
  yum: name={{item}} state=latest
  with_items:
     - git
     - ImageMagick
     - ImageMagick-devel  

- name: create document root
  file: dest={{docroot}} state=directory owner=apache group=apache mode=0755

- name: be sure httpd is configured
  template: src=wordpress.conf.j2 dest=/etc/httpd/conf.d/wordpress.conf

- name: restart httpd
  service: name=httpd state=restarted

- name: remove httpd welcome.conf
  file: path=/etc/httpd/conf.d/welcome.conf state=absent

- name: restart httpd
  service: name=httpd state=restarted

- name: change wordpress files owner
  command: chown -R apache:apache {{docroot}}

- name: be sure mysql-server is installed
  yum: name={{item}} state=installed
  with_items:
     - mysql-server
     - MySQL-python

- name: be sure mysqld is running and enabled
  service: name=mysqld state=started enabled=yes

- name: Create database
  mysql_db: db={{dbname}} state=present encoding=utf8

- name: Create database user
  mysql_user: >
     name={{dbuser}}
     password={{dbpassword}}
     priv={{dbname}}.*:ALL
     state=present

- name: get epel-repo rpm RHEL6
  get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

- name: install epel-repo rpm
  yum: pkg=/tmp/epel-release.rpm state=installed

- name: be sure php is installed
  yum: name={{item}} state=installed enablerepo=epel
  with_items:
    - php
    - php-mysql
    - php-mbstring
    - php-gd
    - php-pear
    - php-pecl-apcu

- name: set timezone in php.ini
  lineinfile: >
    dest=/etc/php.ini
    regexp='^;?date.timezone ='
    line='date.timezone = Asia/Tokyo'
    owner=root
    group=root
    mode=0644

- name: restart httpd
  service: name=httpd state=restarted

- name: download wordpress package
  git : repo=https://github.com/WordPress/WordPress.git dest="{{docroot}}" version={{version}}
  tags: wordpress

- name: change wordpress files owner
  command: chown -R apache:apache {{docroot}}

- name: generate secret keys
  command: curl -o {{docroot}}/secret-keys.php -s https://api.wordpress.org/secret-key/1.1/salt/ creates={{docroot}}/secret-keys.php

- name: read secret keys
  command: cat {{docroot}}/secret-keys.php
  register: secret_keys
  tags: wordpress

- name: configure wp-config.php
  template: src=wp-config.php.j2 dest={{docroot}}/wp-config.php owner=apache group=apache mode=0400

